name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - uses: pnpm/setup@v1
        with:
          version: 11
          runtime: node@22
          cache: true

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Build & Publish Release with Updater Artifacts
        uses: tauri-apps/tauri-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
        with:
          tagName: v__VERSION__
          releaseName: "WriteIn v__VERSION__"
          generateReleaseNotes: true
          releaseDraft: false
          prerelease: false
